public class mod_MoreTools extends BaseMod {
   public static final yr sandstonesword = new lx(800, uk.b).a("StandStoneSword");
   public static final yr sandstonepick = new au(801, uk.b).a("StandStonePick");
   public static final yr sandstonespade = new akd(802, uk.b).a("StandStoneSpade");
   public static final yr sandstoneaxe = new nx(803, uk.b).a("StandStoneAxe");
   public static final yr sandstonehoe = new ic(804, uk.b).a("StandStoneHoe");
   public static final yr obsidiansword = new lx(805, uk.d).a("ObsidianSword");
   public static final yr obsidianpick = new au(806, uk.d).a("ObsidianPick");
   public static final yr obsidianspade = new akd(807, uk.d).a("ObsidianSpade");
   public static final yr obsidianaxe = new nx(808, uk.d).a("ObsidianAxe");
   public static final yr obsidianhoe = new ic(809, uk.d).a("ObsidianHoe");
   public static final yr lapislazulisword = new lx(810, uk.e).a("LapisLazuliSword");
   public static final yr lapislazulipick = new au(811, uk.e).a("LapisLazuliPick");
   public static final yr lapislazulispade = new akd(812, uk.e).a("LapisLazuliSpade");
   public static final yr lapislazuliaxe = new nx(813, uk.e).a("LapisLazuliAxe");
   public static final yr lapislazulihoe = new ic(814, uk.e).a("LapisLazuliHoe");
   public static final yr endstonesword = new lx(815, uk.d).a("EndStoneSword");
   public static final yr endstonepick = new au(816, uk.d).a("EndStonePick");
   public static final yr endstonespade = new akd(817, uk.d).a("EndStoneSpade");
   public static final yr endstoneaxe = new nx(818, uk.d).a("EndStoneAxe");
   public static final yr endstonehoe = new ic(819, uk.d).a("EndStoneHoe");
   public static final yr bedrocksword = new lx(821, uk.d).a("BedrockSword");
   public static final yr bedrockpick = new au(822, uk.d).a("BedrockPick");
   public static final yr bedrockspade = new akd(823, uk.d).a("BedrockSpade");
   public static final yr bedrockaxe = new nx(824, uk.d).a("BedrockAxe");
   public static final yr bedrockhoe = new ic(825, uk.d).a("BedrockHoe");
   public static final yr netherracksword = new lx(826, uk.c).a("NetherRackSword");
   public static final yr netherrackpick = new au(827, uk.c).a("NetherRackPick");
   public static final yr netherrackspade = new akd(828, uk.c).a("NetherRackSpade");
   public static final yr netherrackaxe = new nx(829, uk.c).a("NetherRackAxe");
   public static final yr netherrackhoe = new ic(830, uk.c).a("NetherRackHoe");
   public static final yr bonesword = new lx(831, uk.b).a("BoneSword");
   public static final yr bonepick = new au(832, uk.b).a("BonePick");
   public static final yr bonespade = new akd(833, uk.b).a("BoneSpade");
   public static final yr boneaxe = new nx(834, uk.b).a("BoneAxe");
   public static final yr bonehoe = new ic(835, uk.b).a("BoneHoe");
   public static final yr bedrockingot = new yr(836).a("BedrockIngot");
   public static final yr sandstoneHelmet = new ql(608, cg.b, ModLoader.addArmor("sandstone"), 0).a("Sandstone Helmet");
   public static final yr sandstoneChest = new ql(609, cg.b, ModLoader.addArmor("sandstone"), 1).a("Sandstone Chest");
   public static final yr sandstoneLegs = new ql(610, cg.b, ModLoader.addArmor("sandstone"), 2).a("Sandstone Legs");
   public static final yr sandstoneBoots = new ql(611, cg.b, ModLoader.addArmor("sandstone"), 3).a("Sandstone Boots");
   public static final yr bedrockHelmet = new ql(612, cg.e, ModLoader.addArmor("obsidian"), 0).a("Obsidian Helmet");
   public static final yr bedrockChest = new ql(613, cg.e, ModLoader.addArmor("obsidian"), 1).a("Obsidian Chest");
   public static final yr bedrockLegs = new ql(614, cg.e, ModLoader.addArmor("obsidian"), 2).a("Obsidian Legs");
   public static final yr bedrockBoots = new ql(615, cg.e, ModLoader.addArmor("obsidian"), 3).a("Obsidian Boots");

   public mod_MoreTools() {
      sandstonesword.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/SandStoneSword.png");
      sandstonepick.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/SandStonePick.png");
      sandstonespade.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/SandStoneSpade.png");
      sandstoneaxe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/SandStoneAxe.png");
      sandstonehoe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/SandStoneHoe.png");
      obsidiansword.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/ObsidianSword.png");
      obsidianpick.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/ObsidianPick.png");
      obsidianspade.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/ObsidianSpade.png");
      obsidianaxe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/ObsidianAxe.png");
      obsidianhoe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/ObsidianHoe.png");
      lapislazulisword.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/LapisLazuliSword.png");
      lapislazulipick.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/LapisLazuliPick.png");
      lapislazulispade.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/LapisLazuliSpade.png");
      lapislazuliaxe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/LapisLazuliAxe.png");
      lapislazulihoe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/LapisLazuliHoe.png");
      endstonesword.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/EndStoneSword.png");
      endstonepick.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/EndStonePick.png");
      endstonespade.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/EndStoneSpade.png");
      endstoneaxe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/EndStoneAxe.png");
      endstonehoe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/EndStoneHoe.png");
      bedrocksword.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BedrockSword.png");
      bedrockpick.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BedrockPick.png");
      bedrockspade.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BedrockSpade.png");
      bedrockaxe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BedrockAxe.png");
      bedrockhoe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BedrockHoe.png");
      netherracksword.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/NetherRackSword.png");
      netherrackpick.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/NetherRackPick.png");
      netherrackspade.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/NetherRackSpade.png");
      netherrackaxe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/NetherRackAxe.png");
      netherrackhoe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/NetherRackHoe.png");
      bonesword.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BoneSword.png");
      bonepick.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BonePick.png");
      bonespade.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BoneSpade.png");
      boneaxe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BoneAxe.png");
      bonehoe.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BoneHoe.png");
      bedrockingot.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/BedrockIngot.png");
      ModLoader.addName(sandstonesword, "Sandstone Sword");
      ModLoader.addName(sandstonepick, "Sandstone Pickaxe");
      ModLoader.addName(sandstonespade, "Sandstone Spade");
      ModLoader.addName(sandstoneaxe, "Sandstone Axe");
      ModLoader.addName(sandstonehoe, "Sandstone Hoe");
      ModLoader.addName(obsidiansword, "Obsidian Sword");
      ModLoader.addName(obsidianpick, "Obsidian Pickaxe");
      ModLoader.addName(obsidianspade, "Obsidian Spade");
      ModLoader.addName(obsidianaxe, "Obsidian Axe");
      ModLoader.addName(obsidianhoe, "Obsidian Hoe");
      ModLoader.addName(lapislazulisword, "LapisLazuli Sword");
      ModLoader.addName(lapislazulipick, "LapisLazuli Pickaxe");
      ModLoader.addName(lapislazulispade, "LapisLazuli Spade");
      ModLoader.addName(lapislazuliaxe, "LapisLazuli Axe");
      ModLoader.addName(lapislazulihoe, "LapisLazuli Hoe");
      ModLoader.addName(endstonesword, "Endstone Sword");
      ModLoader.addName(endstonepick, "Endstone Pickaxe");
      ModLoader.addName(endstonespade, "Endstone Spade");
      ModLoader.addName(endstoneaxe, "Endstone Axe");
      ModLoader.addName(endstonehoe, "Endstone Hoe");
      ModLoader.addName(bedrocksword, "Bedrock Sword");
      ModLoader.addName(bedrockpick, "Bedrock Pickaxe");
      ModLoader.addName(bedrockspade, "Bedrock Spade");
      ModLoader.addName(bedrockaxe, "Bedrock Axe");
      ModLoader.addName(bedrockhoe, "Bedrock Hoe");
      ModLoader.addName(netherracksword, "NetherRack Sword");
      ModLoader.addName(netherrackpick, "NetherRack Pickaxe");
      ModLoader.addName(netherrackspade, "NetherRack Spade");
      ModLoader.addName(netherrackaxe, "NetherRack Axe");
      ModLoader.addName(netherrackhoe, "NetherRack Hoe");
      ModLoader.addName(bonesword, "Bone Sword");
      ModLoader.addName(bonepick, "Bone Pickaxe");
      ModLoader.addName(bonespade, "Bone Spade");
      ModLoader.addName(boneaxe, "Bone Axe");
      ModLoader.addName(bonehoe, "Bone Hoe");
      ModLoader.addName(bedrockingot, "Bedrock Ingot");
      ModLoader.addRecipe(new aan(sandstonesword, 1), new Object[]{" x ", " x ", " # ", 'x', pb.Q, '#', yr.D});
      ModLoader.addRecipe(new aan(sandstonepick, 1), new Object[]{"xxx", " # ", " # ", 'x', pb.Q, '#', yr.D});
      ModLoader.addRecipe(new aan(sandstoneaxe, 1), new Object[]{" xx", " #x", " # ", 'x', pb.Q, '#', yr.D});
      ModLoader.addRecipe(new aan(sandstoneaxe, 1), new Object[]{"xx ", " x#", " # ", 'x', pb.Q, '#', yr.D});
      ModLoader.addRecipe(new aan(sandstonespade, 1), new Object[]{" x ", " # ", " # ", 'x', pb.Q, '#', yr.D});
      ModLoader.addRecipe(new aan(sandstonehoe, 1), new Object[]{" xx", " # ", " # ", 'x', pb.Q, '#', yr.D});
      ModLoader.addRecipe(new aan(sandstonehoe, 1), new Object[]{"xx ", " # ", " # ", 'x', pb.Q, '#', yr.D});
      ModLoader.addRecipe(new aan(obsidiansword, 1), new Object[]{" x ", " x ", " # ", 'x', pb.ap, '#', yr.D});
      ModLoader.addRecipe(new aan(obsidianpick, 1), new Object[]{"xxx", " # ", " # ", 'x', pb.ap, '#', yr.D});
      ModLoader.addRecipe(new aan(obsidianaxe, 1), new Object[]{" xx", " #x", " # ", 'x', pb.ap, '#', yr.D});
      ModLoader.addRecipe(new aan(obsidianaxe, 1), new Object[]{"xx ", " x#", " # ", 'x', pb.ap, '#', yr.D});
      ModLoader.addRecipe(new aan(obsidianspade, 1), new Object[]{" x ", " # ", " # ", 'x', pb.ap, '#', yr.D});
      ModLoader.addRecipe(new aan(obsidianhoe, 1), new Object[]{" xx", " # ", " # ", 'x', pb.ap, '#', yr.D});
      ModLoader.addRecipe(new aan(obsidianhoe, 1), new Object[]{"xx ", " # ", " # ", 'x', pb.ap, '#', yr.D});
      ModLoader.addRecipe(new aan(lapislazulisword, 1), new Object[]{" x ", " x ", " # ", 'x', pb.O, '#', yr.D});
      ModLoader.addRecipe(new aan(lapislazulipick, 1), new Object[]{"xxx", " # ", " # ", 'x', pb.O, '#', yr.D});
      ModLoader.addRecipe(new aan(lapislazuliaxe, 1), new Object[]{" xx", " #x", " # ", 'x', pb.O, '#', yr.D});
      ModLoader.addRecipe(new aan(lapislazuliaxe, 1), new Object[]{"xx ", " x#", " # ", 'x', pb.O, '#', yr.D});
      ModLoader.addRecipe(new aan(lapislazulispade, 1), new Object[]{" x ", " # ", " # ", 'x', pb.O, '#', yr.D});
      ModLoader.addRecipe(new aan(lapislazulihoe, 1), new Object[]{" xx", " # ", " # ", 'x', pb.O, '#', yr.D});
      ModLoader.addRecipe(new aan(lapislazulihoe, 1), new Object[]{"xx ", " # ", " # ", 'x', pb.O, '#', yr.D});
      ModLoader.addRecipe(new aan(endstonesword, 1), new Object[]{" x ", " x ", " # ", 'x', pb.bJ, '#', yr.D});
      ModLoader.addRecipe(new aan(endstonepick, 1), new Object[]{"xxx", " # ", " # ", 'x', pb.bJ, '#', yr.D});
      ModLoader.addRecipe(new aan(endstoneaxe, 1), new Object[]{" xx", " #x", " # ", 'x', pb.bJ, '#', yr.D});
      ModLoader.addRecipe(new aan(endstoneaxe, 1), new Object[]{"xx ", " x#", " # ", 'x', pb.bJ, '#', yr.D});
      ModLoader.addRecipe(new aan(endstonespade, 1), new Object[]{" x ", " # ", " # ", 'x', pb.bJ, '#', yr.D});
      ModLoader.addRecipe(new aan(endstonehoe, 1), new Object[]{" xx", " # ", " # ", 'x', pb.bJ, '#', yr.D});
      ModLoader.addRecipe(new aan(endstonehoe, 1), new Object[]{"xx ", " # ", " # ", 'x', pb.bJ, '#', yr.D});
      ModLoader.addRecipe(new aan(bedrocksword, 1), new Object[]{" x ", " x ", " # ", 'x', bedrockingot, '#', yr.D});
      ModLoader.addRecipe(new aan(bedrockpick, 1), new Object[]{"xxx", " # ", " # ", 'x', bedrockingot, '#', yr.D});
      ModLoader.addRecipe(new aan(bedrockaxe, 1), new Object[]{" xx", " #x", " # ", 'x', bedrockingot, '#', yr.D});
      ModLoader.addRecipe(new aan(bedrockaxe, 1), new Object[]{"xx ", " x#", " # ", 'x', bedrockingot, '#', yr.D});
      ModLoader.addRecipe(new aan(bedrockspade, 1), new Object[]{" x ", " # ", " # ", 'x', bedrockingot, '#', yr.D});
      ModLoader.addRecipe(new aan(bedrockhoe, 1), new Object[]{" xx", " # ", " # ", 'x', bedrockingot, '#', yr.D});
      ModLoader.addRecipe(new aan(bedrockhoe, 1), new Object[]{"xx ", " # ", " # ", 'x', bedrockingot, '#', yr.D});
      ModLoader.addRecipe(new aan(netherracksword, 1), new Object[]{" x ", " x ", " # ", 'x', pb.bb, '#', yr.D});
      ModLoader.addRecipe(new aan(netherrackpick, 1), new Object[]{"xxx", " # ", " # ", 'x', pb.bb, '#', yr.D});
      ModLoader.addRecipe(new aan(netherrackaxe, 1), new Object[]{" xx", " #x", " # ", 'x', pb.bb, '#', yr.D});
      ModLoader.addRecipe(new aan(netherrackaxe, 1), new Object[]{"xx ", " x#", " # ", 'x', pb.bb, '#', yr.D});
      ModLoader.addRecipe(new aan(netherrackspade, 1), new Object[]{" x ", " # ", " # ", 'x', pb.bb, '#', yr.D});
      ModLoader.addRecipe(new aan(netherrackhoe, 1), new Object[]{" xx", " # ", " # ", 'x', pb.bb, '#', yr.D});
      ModLoader.addRecipe(new aan(netherrackhoe, 1), new Object[]{"xx ", " # ", " # ", 'x', pb.bb, '#', yr.D});
      ModLoader.addRecipe(new aan(bedrockingot, 4), new Object[]{"x#x", "#x#", "x#x", 'x', pb.ap, '#', yr.n});
      ModLoader.addName(sandstoneHelmet, "Sandstone Helmet");
      sandstoneHelmet.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/sandstoneHelmet.png");
      ModLoader.addRecipe(new aan(sandstoneHelmet, 1), new Object[]{"###", "# #", '#', pb.Q});
      ModLoader.addName(sandstoneChest, "Sandstone Chestplate");
      sandstoneChest.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/sandstoneChest.png");
      ModLoader.addRecipe(new aan(sandstoneChest, 1), new Object[]{"# #", "###", "###", '#', pb.Q});
      ModLoader.addName(sandstoneLegs, "Sandstone Legs");
      sandstoneLegs.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/sandstoneLegs.png");
      ModLoader.addRecipe(new aan(sandstoneLegs, 1), new Object[]{"###", "# #", "# #", '#', pb.Q});
      ModLoader.addName(sandstoneBoots, "Sandstone Boots");
      sandstoneBoots.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/sandstoneBoots.png");
      ModLoader.addRecipe(new aan(sandstoneBoots, 1), new Object[]{"# #", "# #", '#', pb.Q});
      ModLoader.addName(bedrockHelmet, "Bedrock Helmet");
      bedrockHelmet.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/bedrockHelmet.png");
      ModLoader.addRecipe(new aan(bedrockHelmet, 1), new Object[]{"###", "# #", '#', bedrockingot});
      ModLoader.addName(bedrockChest, "Bedrock Chestplate");
      bedrockChest.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/bedrockChest.png");
      ModLoader.addRecipe(new aan(bedrockChest, 1), new Object[]{"# #", "###", "###", '#', bedrockingot});
      ModLoader.addName(bedrockLegs, "Bedrock Legs");
      bedrockLegs.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/bedrockLegs.png");
      ModLoader.addRecipe(new aan(bedrockLegs, 1), new Object[]{"###", "# #", "# #", '#', bedrockingot});
      ModLoader.addName(bedrockBoots, "Bedrock Boots");
      bedrockBoots.bS = ModLoader.addOverride("/gui/items.png", "/Regablith/moretools/bedrockBoots.png");
      ModLoader.addRecipe(new aan(bedrockBoots, 1), new Object[]{"# #", "# #", '#', bedrockingot});
   }

   public String getVersion() {
      return "1.2.3";
   }

   public void load() {
   }
}
